# Generated by Django 3.1.3 on 2022-06-16 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_banners_complaint_created_by_complaint_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.ImageField(null=True, upload_to='')),
                ('email_01', models.EmailField(default='hello@fegno.com', max_length=254)),
                ('email_02', models.EmailField(default='manoj@fegno.com', max_length=254)),
                ('email_03', models.EmailField(default='jomon@fegno.com', max_length=254)),
                ('email_04', models.EmailField(default='jerinisready@gmail.com', max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='banners',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dealers',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_dealers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='banners',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, choices=[(1, 'Admin'), (4, 'Warehouse Manager'), (2, 'Branch Manager'), (16, 'Executive'), (32, 'Dealer'), (8, 'Receptionist')], default=16, max_length=20),
        ),
    ]
