# Generated by Django 4.0.5 on 2022-06-13 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_banners_complaint_created_by_complaint_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dealers',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
