# Generated by Django 4.0.5 on 2022-06-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_banners_is_public_user_dealers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.ImageField(null=True, upload_to='')),
                ('email_01', models.EmailField(default='hello@fegno.com', max_length=254)),
                ('email_02', models.EmailField(default='manoj@fegno.com', max_length=254)),
                ('email_03', models.EmailField(default='jomon@fegno.com', max_length=254)),
                ('email_04', models.EmailField(default='jerinisready@gmail.com', max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[(1, 'Admin'), (4, 'Warehouse Manager'), (2, 'Branch Manager'), (16, 'Executive'), (32, 'Dealer'), (8, 'Receptionist')], default=16, max_length=20),
        ),
    ]
