# Generated by Django 3.1.3 on 2022-06-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220615_2148'),
        ('user', '0005_siteconfiguration_alter_user_user_role'),
    ]

    operations = [
    ]
