# Generated by Django 3.2.13 on 2022-06-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('user', '0006_merge_20220616_1236'),
        # ('user', '0006_merge_20220616_1428'),
        ('user', '0006_auto_20220616_2359'),

    ]


    operations = [
    ]
