# Generated by Django 4.0.5 on 2022-06-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_address_city_user_address_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='photo',
            field=models.ImageField(blank=True, default='public/default/image_not_found.jpg', null=True, upload_to='banners/'),
        ),
    ]
