# Generated by Django 4.0.5 on 2022-06-28 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0012_salesorder_is_quotation'),
        ('user', '0009_complaint_created_at_complaint_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='order.salesorder'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
