# Generated by Django 4.0.5 on 2022-06-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0010_complaint_order_id_alter_complaint_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(
                choices=[('new', 'New'), ('under processing', 'Under Processing'), ('resolved', 'Resolved'),
                         ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
