# Generated by Django 3.1.3 on 2022-06-29 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_complaint_ticket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dealers',
        ),
        migrations.AddField(
            model_name='user',
            name='executives',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_executives_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
