# Generated by Django 3.1.3 on 2022-06-29 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20220629_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='executives',
        ),
        migrations.AddField(
            model_name='user',
            name='executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealers', to=settings.AUTH_USER_MODEL),
        ),
    ]
