# Generated by Django 3.1.3 on 2022-06-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20220629_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.IntegerField(blank=True, choices=[(1, 'Admin'), (4, 'Warehouse Manager'), (2, 'Branch Manager'), (16, 'Executive'), (32, 'Dealer'), (8, 'Receptionist')], default=16, max_length=20),
        ),
    ]
