# Generated by Django 3.1.3 on 2022-07-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_user_excalation_number_alter_banners_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='excalation_number',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='excalation_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='banners',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
