# Generated by Django 3.1.3 on 2022-07-05 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_merge_20220616_1529'),
        ('user', '0018_auto_20220704_2041'),
    ]

    operations = [
    ]
