# Generated by Django 4.0.5 on 2022-06-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('infrastructure', '0004_auto_20220616_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
