# Generated by Django 3.1.3 on 2022-06-15 17:36

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalogue', '0004_auto_20220615_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.category'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True,
                                                            populate_from='title'),
        ),
    ]
