# Generated by Django 4.0.5 on 2022-06-16 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_alter_brand_id_alter_category_id_alter_pdf_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf', to='catalogue.category'),
        ),
    ]
