# Generated by Django 4.0.5 on 2022-06-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalogue', '0009_alter_brand_id_alter_category_id_alter_pdf_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
