# Generated by Django 4.0.5 on 2022-07-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_product_is_active_alter_brand_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=20, null=True),
        ),
    ]
