# Generated by Django 4.0.5 on 2022-06-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='is_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
