# Generated by Django 4.0.5 on 2022-06-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0003_salesorder_invoice_id_salesorder_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='confirmed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='invoice_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='invoice_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='invoice_remaining_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='invoice_status',
            field=models.CharField(
                choices=[('new', 'NEW'), ('credit', 'CREDIT'), ('payment partial', 'Payment Partial'),
                         ('payment done', 'Payment Done')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
