# Generated by Django 3.1.3 on 2022-06-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0007_alter_salesorder_id_alter_salesorderline_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
