# Generated by Django 4.0.5 on 2022-06-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_salesorder_id_alter_salesorderline_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='invoice_status',
            field=models.CharField(choices=[('new', 'New'), ('credit', 'Credit'), ('payment partial', 'Payment Partial'), ('payment done', 'Payment Done')], default='new', max_length=20),
        ),
    ]
