# Generated by Django 4.0.5 on 2022-06-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_salesorder_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='invoice_remaining_amount',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='invoice_status',
            field=models.CharField(choices=[('new', 'New'), ('credit', 'Credit'), ('payment_partial', 'Payment Partial'), ('payment_done', 'Payment Done')], default='new', max_length=20),
        ),
    ]
