# Generated by Django 3.1.3 on 2022-06-29 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0012_salesorder_is_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator]),
        ),
    ]
