# Generated by Django 4.0.5 on 2022-07-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_salesorder_id_alter_salesorderline_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoice/'),
        ),
    ]
