# Generated by Django 4.0.5 on 2022-07-04 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_salesorder_invoice_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoice/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterUniqueTogether(
            name='salesorder',
            unique_together={('order_id', 'invoice_id')},
        ),
    ]
