# Generated by Django 4.0.5 on 2022-06-18 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('order', '0010_alter_salesorder_invoice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.salesorder')),
            ],
        ),
    ]
